//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.7
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class Message extends com.zeroc.Ice.Value
{
    public Message()
    {
        this.message = "";
        this.source = "";
    }

    public Message(String message, String source, boolean broadcast)
    {
        this.message = message;
        this.source = source;
        this.broadcast = broadcast;
    }

    public String message;

    public String source;

    public boolean broadcast;

    public Message clone()
    {
        return (Message)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Demo::Message";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 1740431575L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(message);
        ostr_.writeString(source);
        ostr_.writeBool(broadcast);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        message = istr_.readString();
        source = istr_.readString();
        broadcast = istr_.readBool();
        istr_.endSlice();
    }
}
